### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by noob8** [datitran/face2face-demo#12]
While trying to train i get the following error:
 python face2face-demo/generate_train_data.py --file angela_merkel_speech.mp4 --num 400 --landmark-model shape_predictor_68_face_landmarks.dat

Traceback (most recent call last):
  File "face2face-demo/generate_train_data.py", line 96, in <module>
    predictor = dlib.shape_predictor(args.face_landmark_shape_file)
RuntimeError: Unable to open shape_predictor_68_face_landmarks.dat

So i skipped training and used your validated model and got the following error:
python face2face-demo/reduce_model.py --model-input Desktop/combined/val --model-output Desktop/combined
2018-01-08 13:50:50.597204: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "face2face-demo/reduce_model.py", line 215, in <module>
    saver.restore(sess, checkpoint)
  File "/home/oem/.virtualenvs/facecourse-py3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1662, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

how can i do?

**Comment by noob8** [comment]
so i downloaded a shape_predictor_68_face_landmarks.dat file and added the path location to the command for training. But now i get this error instead?
`GStreamer: Error opening bin: Unrecoverable syntax error while parsing pipeline angela_merkel_speech.mp4
[INFO] elapsed time (total): 0.01
[INFO] approx. FPS: 0.00
`

downloaded dat file from Akshay:
https://github.com/AKSHAYUBHAT/TensorFace/blob/master/openface/models/dlib/shape_predictor_68_face_landmarks.dat

**Comment by Willianflower** [comment]
I encountered the same problem, have you found way to solve it ?
