### ISSUE TITLE
Python script runtime error: frame_resize = cv2.resize(frame, None, fx=1 / DOWNSAMPLE_RATIO, fy=1 / DOWNSAMPLE_RATIO)

### ISSUE THREAD

**Issue by niyaoyao** [datitran/face2face-demo#20]
When I run "generate_train_data.py", it would failed with error:
```
OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file /Users/jenkins/miniconda/1/x64/conda-bld/conda_1486587097465/work/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp, line 3229
Traceback (most recent call last):
  File "generate_train_data.py", line 98, in <module>
    main()
  File "generate_train_data.py", line 27, in main
    frame_resize = cv2.resize(frame, None, fx=1 / DOWNSAMPLE_RATIO, fy=1 / DOWNSAMPLE_RATIO)
cv2.error: /Users/jenkins/miniconda/1/x64/conda-bld/conda_1486587097465/work/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function resize
```

**Comment by niyaoyao** [comment]
It seems that the error only occurred when  I use my video file recorded by myself, the https://dl.dropboxusercontent.com/s/2g04onlkmkq9c69/angela_merkel_speech.mp4 would not cause it.

**Comment by ejjjjkang** [comment]
Is there anyone who solve this issue? I had this problem when I import the video I made.

**Comment by Jens1985** [comment]
Ive got the error even when i use https://dl.dropboxusercontent.com/s/2g04onlkmkq9c69/angela_merkel_speech.mp4 or the pretrained Model.

**Comment by kylemath** [comment]
same problem here, trying to use live webcam
